name: S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

          name: install dependencies
        - run: yarn 

          name: build static 
        - run: yarn build

        - name: Deploy
          uses: keithweaver/aws-s3-github-action@v1.0.0
          with:
              command: cp
              source: build/
              destination: ${{ secrets.S3_URI }}
              aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws_region: ${{ secrets.S3_BUCKET_REGION }}
              flags: --recursive
